# Generated by Django 4.2.1 on 2023-05-19 14:05

from django.db import migrations, models
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
    ]
